### ISSUE TITLE
add profiling

### ISSUE THREAD

**Issue by JosefAssadERST** [TheRacetrack/job-runner-python-lib#15]
Is there a fairly simple way to allow uses of this job type to turn on profiling?

I'm thinking something like [this](https://www.llmtec.com/blogposts/profiling-app-combining-docker-uvicorn-fastapi) which would just end up being another key in the mainfest like

```yaml
name: supersmart
owner_email: nobody@example.com
jobtype: python3:latest

git:
  remote: https://github.com/racetrack/supersmart-model
  branch: master

jobtype_extra:
  profile: true  # <-- this
  requirements_path: 'supersmart/requirements.txt'
  entrypoint_path: 'job_entrypoint.py'
  max_concurrency: 1
  max_concurrency_queue: 10
```

There could be an extra HTTP endpoint like `/profile` serving the results, either raw cProfile output or maybe [snakeviz](https://jiffyclub.github.io/snakeviz/) can be coerced into dumping HTML for the job to serve.
